# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2.1

orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.1

jobs:
    build:
        docker:
            - image: circleci/python:3.7
        steps:
            - checkout
            - run: sudo pip install -r requirements.txt
            - run: sudo pip install .
            - run: pytest --cov-report xml --cov=titan_app/views/ titan_app/tests/
            - run: coveralls
            - run: flake8 --ignore W293 titan_app/views/
            - run: bandit -r titan_app/views/
            - run: sphinx-build -W -b html docs/source/ docs/build/
            - sonarcloud/scan       
            - store_test_results:
                path: .
  
workflows:
    version: 2.1
    main:
        jobs:
            - build:
                context: SonarCloud  
