# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
    build:
        docker:
            - image: circleci/python:3.7
        steps:
            - checkout
            - run: sudo pip install -r requirements.txt
#            - run: cd tests && pytest test_* && cd ..  -- Check if all these cds are needed
            - run: sphinx-build -W -b html docs/source/ docs/build/
