# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
    build:
        docker:
            - image: circleci/python:3.7
        steps:
            - checkout
            - run: sudo pip install -r requirements.txt
            - run: pytest --cov=flask_basic --flake8 tests/test_*
            - run: bandit -r .
            - run: sphinx-build -W -b html docs/source/ docs/build/
